### ISSUE TITLE
Game loops at beginning

### ISSUE THREAD

**Issue by mrniddala** [Tectato/Telepistons#6]
Hello, with the newest version 1.1.1a the game is looping at the beginning. I don't encounter this issue with version 1.0.2.
I see for a half second the title screen and then it loads the game new.

[latest.log](https://github.com/Tectato/Telepistons/files/9183025/latest.log)

**Comment by Tectato** [comment]
Seems to be related to [this issue](https://github.com/Tectato/Telepistons/issues/5). Just a shot in the dark since i couldn't replicate the issue myself, but could you try it with this instead?
[telepistons-1.1.2_dev.zip](https://github.com/Tectato/Telepistons/files/9183885/telepistons-1.1.2_dev.zip)

**Comment by mrniddala** [comment]
The game is still looping at beginning:(

**Comment by Tectato** [comment]
is the log output any different?

**Comment by mrniddala** [comment]
I think it's the same, here is my latest log:

[latest.log](https://github.com/Tectato/Telepistons/files/9183982/latest.log)

**Comment by Tectato** [comment]
It is a tiny bit different which seems promising, mind trying with this?
[telepistons-1.1.2_dev.zip](https://github.com/Tectato/Telepistons/files/9184030/telepistons-1.1.2_dev.zip)
If that doesn't work, could you tell me what modpack you're using?

**Comment by mrniddala** [comment]
The mod loads now fine, thanks for your work:)
I use my own modpack.
